-- MySQL Script generated by MySQL Workbench
-- Thu Dec 18 12:46:52 2014
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema gif_collection
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `gif_collection` ;

-- -----------------------------------------------------
-- Schema gif_collection
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gif_collection` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `gif_collection` ;

-- -----------------------------------------------------
-- Table `gif_collection`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gif_collection`.`users` ;

CREATE TABLE IF NOT EXISTS `gif_collection`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `registered_at` DATETIME NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gif_collection`.`gifs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gif_collection`.`gifs` ;

CREATE TABLE IF NOT EXISTS `gif_collection`.`gifs` (
  `gif_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `url` VARCHAR(100) NULL,
  `created_at` DATETIME NULL,
  PRIMARY KEY (`gif_id`),
  INDEX `fk_gifs_users_idx` (`user_id` ASC),
  CONSTRAINT `fk_gifs_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `gif_collection`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
