-- MySQL Script generated by MySQL Workbench
-- Wed Jan 21 13:12:50 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema gif_collection
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `gif_collection` ;

-- -----------------------------------------------------
-- Schema gif_collection
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gif_collection` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `gif_collection` ;

-- -----------------------------------------------------
-- Table `gif_collection`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gif_collection`.`users` ;

CREATE TABLE IF NOT EXISTS `gif_collection`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `registered_at` DATETIME NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gif_collection`.`gifs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gif_collection`.`gifs` ;

CREATE TABLE IF NOT EXISTS `gif_collection`.`gifs` (
  `gif_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `url` VARCHAR(100) NULL,
  `created_at` DATETIME NULL,
  `is_public` TINYINT(1) NULL DEFAULT 0,
  `is_favorite` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`gif_id`),
  INDEX `fk_gifs_users_idx` (`user_id` ASC),
  CONSTRAINT `fk_gifs_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `gif_collection`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gif_collection`.`tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gif_collection`.`tags` ;

CREATE TABLE IF NOT EXISTS `gif_collection`.`tags` (
  `tag_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `created_at` DATETIME NULL,
  PRIMARY KEY (`tag_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gif_collection`.`gif_tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gif_collection`.`gif_tags` ;

CREATE TABLE IF NOT EXISTS `gif_collection`.`gif_tags` (
  `gif_tags_id` INT NOT NULL AUTO_INCREMENT,
  `gif_id` INT NOT NULL,
  `tag_id` INT NOT NULL,
  PRIMARY KEY (`gif_tags_id`),
  INDEX `fk_gif_tags_gifs1_idx` (`gif_id` ASC),
  INDEX `fk_gif_tags_tags1_idx` (`tag_id` ASC),
  CONSTRAINT `fk_gif_tags_gifs1`
    FOREIGN KEY (`gif_id`)
    REFERENCES `gif_collection`.`gifs` (`gif_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gif_tags_tags1`
    FOREIGN KEY (`tag_id`)
    REFERENCES `gif_collection`.`tags` (`tag_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
